server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://service-user:8081
          predicates:
            - Path=/users/**
        - id: product
          uri: http://service-product:8082
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
        - id: order
          uri: http://service-order:8083
          predicates:
            - Path=/orders/**
