spring:
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://service-product:8082
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
