spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product
              uri: http://service-product:8082
              predicates:
                - Path=/products/**
              filters:
                - StripPrefix=1
