server:
  port: 8083

spring:
  application:
    name: service-order
  datasource:
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Taipei
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: basic

# Feign 熔斷/超時（給你一個示範 instance 名稱，可對應 @FeignClient）
resilience4j:
  circuitbreaker:
    instances:
      userClient:
        slidingWindowSize: 20
        failureRateThreshold: 50
  timelimiter:
    instances:
      userClient:
        timeoutDuration: 3s

# 事件交換器/路由鍵（與 product 對齊）
app:
  mq:
    exchange: orders.x
    routing-key: created
