server:
  port: 8082

spring:
  application:
    name: service-product
  datasource:
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Taipei
    

# 若有用 @Bean 宣告 Queue/Exchange，也可把名稱放在這裡集中管理
app:
  mq:
    exchange: orders.x
    queue: orders.created.q
    routing-key: created
