server:
  port: 8082

spring:
  application:
    name: service-product
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Taipei

app:
  mq:
    exchange: orders.x
    queue: orders.created.q
    routing-key: created
